### ISSUE TITLE
Company User - /jobs - Displays the jobs they posted with links to /jobs/:id

### ISSUE THREAD

**Issue by prescottsun** [Da-Colon/codetrain#80]
For company user, render job board with only company job posts. Button links to submit form.

**Comment by neporshiso** [comment]
- [ ] List of jobs company user has posted displayed on /jobs
- [ ] Link to create a Job Post. 
- [ ] Job Posts need an "edit" component similar to how Daniel handled resources

**Comment by neporshiso** [comment]
Well this took longer than I thought it would
